### PR TITLE
修复错误的hash

### PR DESCRIPTION
**Pull request by lifansama**

### CODE REVIEW

**Comment by h404bi** [comment]
Why close the pull request 😕

**Comment by escape0707** [comment]
I think maybe only the good old bot have the authority to commit to the
repo through the update method from scoop official wiki that I just quoted.
You don’t want to ultimately trust too many people because if one of them
want to do evil or they are good but one of their account is compromised,
then you are risking of downloading and running a malicious software
directly from scoop.

You WILL want to limit the right to commit to this repo to fewer people —
maybe nobody but a only neutral bot!

**Comment by h404bi** [comment]
Oh yeah, you are right. Currently, only the bot and I have the authority of committing. It's ok to accept contributions from the community. And pull requests will not be committed without my reviews.

**Comment by escape0707** [comment]
> Oh yeah, you are right. Currently, only the bot and I have the authority of committing. It's ok to accept contributions from the community. And pull requests will not be merged without my reviews.

Wait, what? When I saw the email notification I didn’t recognized from the sender address that you are the bucket owner XD.

And isn’t an automatic commit of your repo’s update bot caused this PR to close because the PR’s HEAD has already changed? I don’t know very much about GitHub’s PR workflow, though XD.

But I do think lifansama and I and many others are all glad to contribute to your helpful bucket! 😝

**Pull request closed without merging**
