### PR TITLE
Add manifest firefox-nightly-zh-cn

### PR DESCRIPTION
**Pull request by Ni1fheim**
Add Firefox Nightly chinese(simplified) version.

### CODE REVIEW

**Comment by h404bi** [comment]
```json
{
    "description": "Nightly builds of Firefox: the popular open source web browser.",
    "homepage": "https://www.mozilla.org/zh-CN/firefox/nightly/",
    "version": "nightly",
    "license": "MPL-2.0",
    "architecture": {
        "64bit": {
            "url": "https://download.mozilla.org/?product=firefox-nightly-latest-l10n-ssl&os=win64&lang=zh-CN#/firefox.7z"
        },
        "32bit": {
            "url": "https://download.mozilla.org/?product=firefox-nightly-latest-l10n-ssl&os=win&lang=zh-CN#/firefox.7z"
        }
    },
    "extract_dir": "core",
    "bin": [
        [
            "firefox.exe",
            "firefox-nightly"
        ]
    ],
    "shortcuts": [
        [
            "firefox.exe",
            "Firefox Nightly"
        ]
    ]
}

```

**Comment by Ni1fheim** [comment]
In this repo, the firefox-beta-zh-cn and firefox-developer-zh-cn versions are identified as nightly, but Firefox Nightly is updated daily, should I mark version as “7x.00(date)" ?

**Comment by h404bi** [comment]
You should mark it as nightly so the manifest does not need to be updated frequently. Updates can be done by Firefox itself.

**Comment by Ni1fheim** [comment]
You are right, I have been modified.

**Pull request merged**
